# Generated by Django 3.1.12 on 2025-03-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250328_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
