# Generated by Django 3.1.12 on 2025-03-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('stats', models.JSONField(default={'HP': 20, 'Spe': 5, 'atk': 5, 'def': 5, 'spA': 5, 'spD': 5})),
            ],
        ),
    ]
