# Generated by Django 3.1.12 on 2025-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250329_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_credentials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
